### ISSUE TITLE
Class of Mail::Audit->new(...)

### ISSUE THREAD

**Issue by kenahoo** [rjbs/Mail-Audit#2]
After about a decade of getting CPAN Testers fail messages, I decided to try to fix my `Mail::Query` module.

It seems to be getting tripped up because it subclasses `Mail::Audit`, but `Mail::Audit->new(...)` no longer returns an object of class `Mail::Audit`.  It returns a `Mail::Audit::MailInternet` object, which in turn has `use parent qw(Mail::Audit Mail::Internet);`.

Is this situation stable?  I.e. should I declare `Mail::Audit::MailInternet` as my base class now?

Thanks.

**Comment by kenahoo** [comment]
I'm also curious - why does `Mail::Audit::MailInternet` exist?  Why not just have `@Mail::Audit::ISA = qw(Mail::Internet)` rather than the diamond inheritance?

**Comment by rjbs** [comment]
_long, world-weary sigh_

It comes down to this:

> Simon Cozens simon@cpan.org wrote versions 1 and 2.
> 
> Meng Weng Wong mengwong@pobox.com turned a petite demure v2.0 into a
> raging bloated v2.1, adding MIME support, emergency recovery, filename
> interpolation, and autoreply features.

MIME support is a steaming mess.  When Mail::Audit is initializing, it does this:

``` perl
  if ($opts{alwaysmime} or $mime_test->($self)) {
    unless ($opts{nomime}) {
      $self->_log(3,
        "message is MIME.  MIME-Version is " . ($self->get("MIME-Version"))
      );
      eval {
        require Mail::Audit::MimeEntity;
        Mail::Audit::MimeEntity->import;
      };
      die "$@" if $@;
      $self = Mail::Audit::MimeEntity->_autotype_new($self, $opts{mimeoptions});
    } else {
      $self->_log(3, "message is MIME, but 'nomime' option was set.");
    }
  }
```

If the message seems to be MIME (i.e., tons of mail these days) then it gives you a Mail::Audit::MimeEntity.  Otherwise, you get a Mail::Audit::MailInternet.

I don't know why you suggested that there is diamond inheritance.

You either get:
1. M:A:MailInternet isa (Mail::Audit, Mail::Internet)
2. M:A:MimeEntity isa (Mail::Audit, MIME::Entity)

The grossness is that Mail::Internet and MIME::Entity have similar, but quite distinct interfaces.  The thing you get back from Mail::Audit has an unpredictable interface!  You have to write code that picks one path or the other as you go, rather than relying on one consistent set of methods.

This is why, in those cases where I have not been able to purge Mail::Audit from code, I turn on the "always mime" option, so that I always get the MIME interface.  It can handle non-MIME messages.

**Comment by rjbs** [comment]
I think my comment above should answer your question: turn on always_mime and expect a Mail::Audit::MimeEntity.
